additional_guides:
  - https://github.com/zalando-incubator/atlas-ios/wiki/Installation
  - https://github.com/zalando-incubator/atlas-ios/wiki/Configuration
  - https://github.com/zalando-incubator/atlas-ios/wiki/AtlasUI-usage
  - https://github.com/zalando-incubator/atlas-ios/wiki/Project-structure

