codecov:
  branch: master
  bot: bonkey

  status:
    project:
      default:
        target: 75
        threshold: 1

coverage:
  precision: 2
  round: down
  range: 50...80

  ignore:
    - .*/SwiftyJSON.*
    - AtlasUI/AtlasUI/Utils/Reachability.swift

