codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: 50...80

  ignore:
    - Sources/ZalandoCommerceUI/ZalandoCommerceUI/Utils/Reachability.swift

  status:
    project:
      default:
        target: 75
        threshold: 1

