Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/AlignParameters:
  Enabled: false

