line_length: 140

variable_name:
  min_length: 3
  excluded:
    - id

type_body_length:
  warning: 100
  error: 200

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - T

file_length:
  warning: 200
  error: 300

disabled_rules:
  - missing_docs # it's broken currently: https://github.com/realm/SwiftLint/issues/728

excluded:
  - Carthage
    # Unfortunately swiftlint checks directory only in relation to the script run,
    # so we need all the combinations of SwiftyJSON path here
  - AtlasSDK/Utils/SwiftyJSON
  - Utils/SwiftyJSON
  - AtlasSDK/AtlasSDKTests/SwiftyJSON
  - AtlasSDKTests/SwiftyJSON
  - SwiftyJSON
  - AtlasSDKTests
  - AtlasMockAPITests
  - AtlasDemoUITests
  - AtlasUITests
  - AtlasDemo
  - AtlasMockAPI

opt_in_rules:
  - force_unwrapping
  - empty_count
  - missing_docs
  - attributes
  - closure_end_indentation
  - closure_spacing
  - first_where
  - nimble_operator
  - number_separator
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace
  - explicit_init
