line_length: 140

variable_name:
  min_length: 3
  excluded:
    - id

type_body_length:
  warning: 100
  error: 200

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - T

excluded:
  - Carthage
  - AtlasSDKTests
  - MockAPITests
  - AtlasDemoUITests
  - AtlasUITests
  - AtlasDemo
  - MockAPI

opt_in_rules:
  - force_unwrapping
  - empty_count
  - attributes
  - closure_end_indentation
  - closure_spacing
  - first_where
  - nimble_operator
  - number_separator
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace
  - explicit_init
  - object_literal
