language: objective-c
osx_image: xcode7.3

notifications:
  email: false

cache:
  bundler: true
  # Temporarily disabled to test binary frameworks in repo
  # directories:
  #   - Carthage

# Temporarily disabled to test binary frameworks in repo
# before_install:
#   - bundle install --without=tools
# before_script:
#   - travis_wait 30 ./calypso.rb deps uncached

script:
  - bundle exec ./calypso.rb xcode test UnitTests 3
  - bash <(curl -s https://codecov.io/bash) -J AtlasSDK -J AtlasUI

# Carthage automatic release

# env:
#   global:
#     - FRAMEWORK_NAME=AtlasSDK

# before_deploy:
#   - carthage build --no-skip-current --platform iOS
#   - carthage archive $FRAMEWORK_NAME

# skip_cleanup: true
# on:
#   repo: repo/repo
#   tags: true
