language: objective-c
osx_image: xcode7.3

notifications:
  email: false

cache:
  bundler: true
  directories:
  - Carthage

install:
  - bundle install
  - travis_wait 30 ./calypso.rb deps uncached

after_build:
  - bash <(curl -s https://codecov.io/bash)

script:
  - ./calypso.rb xcode test
