language: objective-c
osx_image: xcode7.3

notifications:
  email: false

cache:
  bundler: true
  directories:
  - Carthage

install:
  - bundle install --without=tools
  - travis_wait 30 ./calypso.rb deps uncached

script:
  - ./calypso.rb xcode test 3
  - bash <(curl -s https://codecov.io/bash) -J AtlasSDK -J AtlasUI
