language: objective-c

notifications:
  email: false

before_install:
  - bundle update

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

xcode_project: AtlasCheckoutDemo.xcodeproj
xcode_scheme: AtlasCheckoutDemo

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild -workspace AtlasSDK.xcworkspace -parallelizeTargets clean build test -scheme AtlasCheckoutDemo -enableCodeCoverage YES

