language: objective-c

notifications:
  email: false

before_install:
  - bundle update
  # - carthage update

# after_success:
#   - bash <(curl -s https://codecov.io/bash)

xcode_project: AtlasDemo.xcodeproj
xcode_scheme: AtlasDemo

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

install: ./calypso.rb deps build

# script:
#   - xcodebuild -workspace AtlasSDK.xcworkspace -parallelizeTargets clean build test -scheme AtlasCheckoutDemo -enableCodeCoverage YES

