language: objective-c
osx_image: xcode8

notifications:
  email: false

cache:
  bundler: true

script:
  - bundle exec ./calypso.rb xcode test 3

after_script:
  - bash <(curl -s https://codecov.io/bash) -J AtlasSDK -J AtlasUI

## Carthage automatic deployment:
##
## before_deploy:
##   - carthage build --no-skip-current --platform iOS
##   - carthage archive AtlasSDK AtlasUI
##
## skip_cleanup: true
##
## on:
##   repo: repo/repo
##   tags: true
