language: objective-c
osx_image: xcode8

notifications:
  email: false

cache:
  bundler: true

script:
  - bundle exec ./calypso.rb xcode test 3

after_script:
  - bash <(curl -s https://codecov.io/bash) -J AtlasSDK -J AtlasUI

before_deploy:
  - bundle exec ./calypso.rb carthage build

deploy:
  provider: releases
  on:
    tags: true
  skip_cleanup: true
  file: AtlasSDK.framework.zip
  api_key:
    secure: n/GY6pfdeeoieAmaJhODPp8Gk/uXn7CsVkDh96VlJz0ulnloOBPPS7JOthmViH+lC4Xt7LZNVcJM/8DMCa79yuP226hJwM2xOFBlVD7t/8mqfDm7C/mthla9g5TKv44eOmtvbV3ZsRQpjHbw7OyG+VeaC44dOIsLhiC4IvzbNoAqQeu4B/tqiyeK62azcux0MHp0vgOpq5YUaKHV9/nUFD0JQYbrOWPgG5A/ojSL9RXLZJ0AY8v2cadN3V+tKm8sx6G6Z5hpvX2kePEgQ5My5amGuBw56Dqqq/73/nNoS11TNZ/rbwFJRySvXeTAvNR0v94YB6SwEu1SYdkSbIxbWoRm0tescQqxGI+n50BEN6CvHh6JsQQnwPWoxn24lNNC2+eIQBp4WcoNS8Tdf4RzJ5nKdMDKL+vt26fCSN9Mw8HUF2uyiLx6syrHLUAdxmfrPan1PZ3P/S1CMIG2Zpy0e++ZdFBgV7jcyGbdvuF7baGkipzQ6yfUdWZjUi+QxTTQOrE5UX1Gvobi3IKMWcUT+fhzTs6HnmGDbvOS3cZExNJPct1UO8NCmKarWZ0q1CQMkVbEf4of/zYPYL1Tukh8qf6aq2RpMMHG9r58u/PSuigIn3emV92FQ3bgYmiid4+Cct6yWSSvah/roVX+5NKtJgyrC3U70J973wwrS3mtJ50=
