language: objective-c

before_install:
  - bundle update

branches:
  only:
    - master

xcode_project: AtlasCheckoutDemo.xcodeproj
xcode_scheme: AtlasCheckoutDemo

osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

script:
  - xcodebuild -workspace AtlasSDK.xcworkspace -parallelizeTargets clean build test -scheme AtlasCheckoutDemo -enableCodeCoverage YES
